const seedNotes = [
  {
    id: "note_marais_history",
    title: "Histoire du Marais",
    category: "🏛️ Patrimoine",
    icon: "🏛️",
    type: "guide",
    author: "Office du Tourisme",
    duration: 180,
    baseHealth: 95,
    isLive: false,
    lat: 48.85818,
    lng: 2.35812,
    likes: 42,
    downvotes: 3,
    reports: 0,
    plays: 128,
    listeners: 0
  },
  {
    id: "note_jazz_1952",
    title: "Concert Jazz 1952",
    category: "🎵 Musique",
    icon: "🎷",
    type: "music",
    author: "Archives Paris",
    duration: 240,
    baseHealth: 88,
    isLive: false,
    lat: 48.8564,
    lng: 2.3529,
    likes: 55,
    downvotes: 6,
    reports: 1,
    plays: 214,
    listeners: 0
  },
  {
    id: "note_resistance_story",
    title: "Témoignage Résistance",
    category: "📜 Histoire",
    icon: "📜",
    type: "story",
    author: "Mémorial",
    duration: 300,
    baseHealth: 92,
    isLive: false,
    lat: 48.8601,
    lng: 2.3542,
    likes: 63,
    downvotes: 2,
    reports: 0,
    plays: 301,
    listeners: 0
  },
  {
    id: "note_cafe_flore",
    title: "Guide Café Flore",
    category: "☕ Culture",
    icon: "☕",
    type: "guide",
    author: "Guide Local",
    duration: 120,
    baseHealth: 85,
    isLive: false,
    lat: 48.8548,
    lng: 2.3331,
    likes: 38,
    downvotes: 5,
    reports: 0,
    plays: 167,
    listeners: 0
  },
  {
    id: "live_jazz_session",
    title: "Jazz Session",
    category: "🎵 Live",
    icon: "🎷",
    type: "live",
    author: "Piano Bar",
    duration: 180,
    baseHealth: 80,
    isLive: true,
    lat: 48.8577,
    lng: 2.3502,
    likes: 26,
    downvotes: 1,
    reports: 0,
    plays: 89,
    listeners: 12
  },
  {
    id: "live_city_podcast",
    title: "Podcast Urbain",
    category: "🎧 Live",
    icon: "🎧",
    type: "live",
    author: "Radio Marais",
    duration: 180,
    baseHealth: 78,
    isLive: true,
    lat: 48.8593,
    lng: 2.3605,
    likes: 34,
    downvotes: 4,
    reports: 1,
    plays: 122,
    listeners: 23
  }
];

module.exports = {
  seedNotes
};
